[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["backend/**"]

[deploy]
healthcheckPath = "/api/docs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
